import React, { useState } from "react";
import { motion } from "framer-motion";
import {
  ShieldCheck,
  ArrowRight,
  CheckCircle2,
  AlertCircle,
  Info,
  Scale,
  Stethoscope,
  Database,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

const Disclaimer = () => {
  const navigate = useNavigate();
  const [accepted, setAccepted] = useState(false);

  const handleContinue = () => {
    if (accepted) {
      navigate("/predict");
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center py-20 px-4 transition-colors duration-500 relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_50%_0%,rgba(225,29,72,0.03),transparent)] pointer-events-none"></div>

      <motion.div
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        className="max-w-2xl w-full bg-white dark:bg-slate-900 rounded-[32px] shadow-xl shadow-slate-200/50 dark:shadow-none overflow-hidden border border-slate-100 dark:border-slate-800"
      >
        <div className="bg-slate-900 dark:bg-slate-800 p-8 text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-48 h-48 bg-health-600 rounded-full blur-[80px] opacity-20 translate-x-1/3 -translate-y-1/3"></div>

          <div className="flex items-center gap-4 relative z-10">
            <div className="p-3 bg-white/10 backdrop-blur-md rounded-2xl">
              <ShieldCheck className="w-6 h-6 text-health-400" />
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-tight italic">
                Clinical Disclosure
              </h2>
              <p className="text-slate-400 text-[10px] font-black uppercase tracking-widest mt-0.5">
                Verification Required
              </p>
            </div>
          </div>
        </div>

        <div className="p-8 space-y-8">
          <div className="space-y-6">
            <DisclaimerSection
              icon={<Stethoscope size={20} className="text-health-500" />}
              title="Informational Tool Only"
              text="This analysis is generated by a neural network based on statistical patterns. It is NOT a clinical diagnosis."
            />

            <DisclaimerSection
              icon={<Database size={20} className="text-health-500" />}
              title="Data Limitations"
              text="Risk probability is estimated from 70k+ historical records. High correlation does not equal medical certainty."
            />

            <div className="bg-slate-50 dark:bg-slate-950 rounded-2xl p-6 border border-slate-100 dark:border-slate-800">
              <h3 className="text-xs font-black text-slate-800 dark:text-slate-200 mb-4 flex items-center gap-2 uppercase tracking-[0.2em] italic">
                <AlertCircle className="w-4 h-4 text-amber-500" />
                Ethical Bounds
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {[
                  "Educational context only",
                  "Privacy first, no cached data",
                  "Call 911 for emergencies",
                  "Independent MD review needed",
                ].map((item, i) => (
                  <li
                    key={i}
                    className="flex items-center gap-3 text-slate-600 dark:text-slate-400 text-xs font-bold italic"
                  >
                    <CheckCircle2
                      size={14}
                      className="text-health-500 shrink-0"
                    />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="pt-6 border-t border-slate-100 dark:border-slate-800">
            <label className="flex items-center gap-4 cursor-pointer group">
              <div className="relative flex items-center">
                <input
                  type="checkbox"
                  className="peer sr-only"
                  checked={accepted}
                  onChange={(e) => setAccepted(e.target.checked)}
                />
                <div className="w-7 h-7 border-2 border-slate-200 dark:border-slate-700 rounded-xl peer-checked:bg-health-600 peer-checked:border-health-600 transition-all duration-300 group-hover:border-health-400"></div>
                <CheckCircle2
                  size={18}
                  className="text-white absolute top-1 left-1 opacity-0 peer-checked:opacity-100 transition-opacity"
                />
              </div>
              <span className="text-slate-500 dark:text-slate-500 font-bold text-xs select-none group-hover:text-slate-900 dark:group-hover:text-white transition-colors py-0.5 leading-relaxed italic">
                I acknowledge that this is a statistical simulation tool.
              </span>
            </label>
          </div>

          <div className="flex justify-end pt-2">
            <motion.button
              whileHover={accepted ? { x: 5 } : {}}
              onClick={handleContinue}
              disabled={!accepted}
              className={`
                flex items-center gap-3 px-10 py-4 rounded-[20px] font-black text-sm transition-all duration-300 shadow-xl
                ${
                  accepted
                    ? "bg-slate-900 dark:bg-health-600 text-white hover:bg-black dark:hover:bg-health-700 shadow-slate-200 dark:shadow-none"
                    : "bg-slate-100 dark:bg-slate-800 text-slate-300 dark:text-slate-600 cursor-not-allowed shadow-none"
                }
              `}
            >
              Enter Diagnostic Portal
              <ArrowRight size={18} />
            </motion.button>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

// const DisclaimerSection = ({ icon, title, text }) => (
//   <div className="flex gap-5">
//     <div className="shrink-0 p-3 bg-health-50 dark:bg-health-500/10 rounded-xl h-fit">
//       {icon}
//     </div>
//     <div>
//       <h3 className="text-lg font-black text-slate-900 dark:text-white mb-1 italic tracking-tight">
//         {title}
//       </h3>
//       <p className="text-slate-500 dark:text-slate-400 font-medium text-xs leading-relaxed">
//         {text}
//       </p>
//     </div>
//   </div>
// );

const DisclaimerSection = ({ icon, title, text }) => (
  <div className="flex gap-6 group">
    <div className="shrink-0 p-4 bg-health-50 dark:bg-health-500/10 rounded-2xl h-fit group-hover:bg-health-100 dark:group-hover:bg-health-500/20 transition-colors">
      {icon}
    </div>
    <div>
      <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-2 italic tracking-tight">
        {title}
      </h3>
      <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
        {text}
      </p>
    </div>
  </div>
);

export default Disclaimer;
